RefHeader header

Vector3D center
Vector3D closest_point
Vector3D closest_box
Vector3D front_bumper
Vector3D rear_bumper

uint8 move_status
uint8 cut_in
uint8 cut_out
uint8 cipv

Vector3D velocity
Vector3D project_velocity

Vector3D acceleration
float64 angular_velocity
Vector3D direction

float64 height
float64 length
float64 width

bool is_radar_matching
bool is_tracked

Vector3D radar_velocity

uint8 type

float64 type_confidence

Vector3D pose

float64 roll
float64 pitch
float64 yaw
float64 car_twist




